stages:
  - test
  - build

e2e_tests:
  stage: test
  image: circleci/node
  before_script:
    - npm install
  script:
    - npm test

# Build a project for production testing
build-dev:
  image: node:latest
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - cat $ENV_DEV >> ./.env
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 days
  only:
    - develop


# Build a project for production
build-prod:
  image: node:latest
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - cat $ENV_PROD >> ./.env
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 30 days
  only:
    - release
