stages:
  - build
  - deploy

build:
  image: node:latest
  stage: build
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - cat $ENV_DEV >> ./.env
    - npm install --progress=false
  only:
    - develop
  artifacts:
    expire_in: 1 week
    paths:
      - dist


deploy:
  image: node:latest
  stage: deploy
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    #- cat "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    #- chmod 644 ~/.ssh/known_hosts
  script:
    - rsync -rav --delete dist/ gitlab-runner@194.58.104.82:/home/gitlab-runner/test
  only:
    - develop
  artifacts:
    paths:
      - dist

