stages:
  - build
  - deploy

services:
  - docker:dind

build:
  image: docker:latest
  stage: build
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ls -la
    - docker -H ssh://gitlab-runner@194.67.91.197 version
    - docker -H ssh://gitlab-runner@194.67.91.197 ps
    - docker -H ssh://gitlab-runner@194.67.91.197 login -u $GITLAB_USER_LOGIN -p $REGISTRY_TOKEN $CI_REGISTRY
  script:
    - cat $ENV_DEV >> ./.env
    - docker -H ssh://gitlab-runner@194.67.91.197 build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:app.$CI_PIPELINE_ID .
    - docker -H ssh://gitlab-runner@194.67.91.197 push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:app.$CI_PIPELINE_ID
  only:
    - develop


deploy:
  stage: deploy
  image: docker:latest
  variables:
    DOCKER_HOST: tcp://docker:2375
  before_script:
    - docker login -u $GITLAB_USER_LOGIN -p $REGISTRY_TOKEN $CI_REGISTRY
  script:
    - docker stop $CI_PROJECT_NAME || true
    - docker run -p 3000:80 --rm -d --name $CI_PROJECT_NAME $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:app.$CI_PIPELINE_ID
  only:
    - develop
