pipelines:
  branches:
    develop:
      - step:
          name: "Build for review"
          runs-on:
            - self.hosted
            - dev
          image: node:16.13.0
          caches:
            - node
          artifacts:
            - dist
          script:
            - echo $VUE_ENV_REVIEW | base64 -di > ./.env
            - npm install
            - npm run build
            - pipe: atlassian/rsync-deploy:0.7.0
              variables:
                USER: $SSH_USER
                SERVER: $SSH_SERVER
                REMOTE_PATH: "~/www/rmok.gui"
                LOCAL_PATH: "dist"
                EXTRA_ARGS: "--delete"
