pipelines:
  branches:
    release/*:
      # Up version
      - step:
          name: "Up version"
          trigger: automatic
          runs-on:
            - self.hosted
            - dev
          script:
            - apt-get update
            - apt-get install -y jq
            - old_version=$(jq -r '.version' package.json)
            - new_version="$(date +'v%Y.%-m.%-d.')$BITBUCKET_BUILD_NUMBER"
            - sed -i "s/$old_version/$new_version/g" ./package.json
            - git commit -am "Release $new_version"
            - git push

      # Build
      - step:
          name: "Build"
          image: node:16.13.0
          trigger: automatic
          deployment: "Review"
          caches:
            - pip
            - node
          runs-on:
            - self.hosted
            - dev
          artifacts:
            - dist/**
          script:
            - git pull
            - npm install --no-progress
            - cat << EOT >> ./.env
              VUE_APP_API_ENDPOINT=$VUE_APP_API_ENDPOINT
              VUE_APP_SSE_ENDPOINT=$VUE_APP_SSE_ENDPOINT
              VUE_APP_MS_WHATSAPP_ENDPOINT=$VUE_APP_MS_WHATSAPP_ENDPOINT
              VUE_APP_MS_WS_ENDPOINT=$VUE_APP_MS_WS_ENDPOINT
              EOT
            - npm run build

      # Deploy
      - step:
          name: "Deploy"
          trigger: automatic
          caches:
            - pip
          runs-on:
            - self.hosted
            - dev
          artifacts:
            - dist/**
          script:
            - pipe: atlassian/rsync-deploy:0.7.0
              variables:
                USER: $REVIEW_SSH_USER
                SERVER: $REVIEW_SSH_SERVER
                REMOTE_PATH: "~/www/rmok.gui"
                LOCAL_PATH: "./dist/"
                EXTRA_ARGS: "--delete"
                DEBUG: "false"

      # Update production!!!
      - step:
          name: "Update production!!!"
          trigger: manual
          runs-on:
            - self.hosted
            - dev
          script:
            - apt-get update
            - apt-get install -y jq
            - git pull
            - version=$(jq -r '.version' package.json)
            - git tag -a $version -m "Release $version"
            - git push --tags


  tags:
    v*:
      # Build
      - step:
          name: "Build"
          image: node:16.13.0
          trigger: automatic
          deployment: "Production"
          caches:
            - pip
            - node
          runs-on:
            - self.hosted
            - dev
          artifacts:
            - dist/**
          script:
            - npm install --no-progress
            - cat << EOT >> ./.env
              VUE_APP_API_ENDPOINT=$VUE_APP_API_ENDPOINT
              VUE_APP_SSE_ENDPOINT=$VUE_APP_SSE_ENDPOINT
              VUE_APP_MS_WHATSAPP_ENDPOINT=$VUE_APP_MS_WHATSAPP_ENDPOINT
              VUE_APP_MS_WS_ENDPOINT=$VUE_APP_MS_WS_ENDPOINT
              EOT
            - npm run build

      # Deploy
      - step:
          name: "Deploy"
          trigger: automatic
          caches:
            - pip
          runs-on:
            - self.hosted
            - dev
          artifacts:
            - dist/**
          script:
            - pipe: atlassian/rsync-deploy:0.7.0
              variables:
                USER: $PROD_SSH_USER
                SERVER: $PROD_SSH_SERVER
                REMOTE_PATH: "~/www/rmok.gui"
                LOCAL_PATH: "./dist/"
                EXTRA_ARGS: "--delete"
                DEBUG: "false"
