server {
    listen                 80;

    client_max_body_size   208M;

    access_log             /dev/stdout combined;
    error_log              /dev/stdout error;

    root                   /www;

    location / {
        try_files          $uri $uri/ /index.html;
    }
}
